name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: sandragrzelak
          password: dckr_pat_dSJN2uwfHCYF0-fIARjNl2l9Rl4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./KamtjatkaAPI/Dockerfile
          push: true
          tags: sandragrzelak/kamtjatkaapi:latest
          
      - 
        name: 'Az CLI login without subscription'
        uses: azure/login@v1
        with:
          client-id: 310093@VIAUC.DK
          tenant-id: 97e1982b-375c-460e-9071-9067de86388b
          allow-no-subscriptions: true
          
      - run: |
          az container restart --name kamtjatkaapi --resource-group server_bpr
